
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace App.Core.Data
{

using System;
    using System.Collections.Generic;
    
public partial class ListingSpec
{

    public int ListingID { get; set; }

    public string Attribute { get; set; }

    public string Text { get; set; }

    public short Sort { get; set; }



    public virtual Listing Listing { get; set; }

}

}
