//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Core.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopDBEntities : DbContext
    {
        public ShopDBEntities()
            : base("name=ShopDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Listing> Listings { get; set; }
        public virtual DbSet<ListingImage> ListingImages { get; set; }
        public virtual DbSet<ListingOption> ListingOptions { get; set; }
        public virtual DbSet<ListingSpec> ListingSpecs { get; set; }
        public virtual DbSet<RefCategory> RefCategories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserSimple> UserSimples { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<ListingImageDeleted> ListingImageDeleteds { get; set; }
        public virtual DbSet<RefType> RefTypes { get; set; }
        public virtual DbSet<RefValue> RefValues { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RegionZone> RegionZones { get; set; }
        public virtual DbSet<OAuthMembership> OAuthMemberships { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
    }
}
