//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonsterAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingOption
    {
        public int ListingID { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> OriginalPrice { get; set; }
        public Nullable<decimal> DiscountedPrice { get; set; }
        public Nullable<short> Quantity { get; set; }
        public Nullable<int> LinkToImage { get; set; }
        public short Sort { get; set; }
    
        public virtual Listing Listing { get; set; }
    }
}
